app_bomberos/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path('gestion_vehiculos/',views.gestion_vehiculos,name="gestion_vehiculos"),
    path('add_vehiculo/',views.add_vehiculo,name="add_vehiculo"),
    path('update_vehiculo/<int:id>',views.update_vehiculo,name="update_vehiculo"),
    path('delete_vehiculo/<int:id>',views.delete_vehiculo,name="delete_vehiculo"),
    path('detail_vehiculo/<int:id>',views.detail_vehiculo,name="detail_vehiculo"),
    path('register_m/',views.register_m, name='register_m'),
    path('login_custom/', views.login_custom, name='login_custom'),
    path('logout_custom/', views.logout_custom, name='logout_custom'),
    path('compañia/',views.compañia,name="compañia"),
    path('historial_mantenciones/',views.historial_mantenciones,name="historial_mantenciones"),
    path('historial_correctiva/',views.historial_correctiva,name="historial_correctiva"),
    path('historial_externo/',views.historial_externo,name="historial_externo"),

]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app_bomberos.urls")),
]

if settings.DEBUG==True:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_bomberos/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone



# Create your models here.
class Compañia(models.Model):
    nombre_compañia = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    # Agrega otros campos según tus necesidades

    def __str__(self):
        return self.nombre_compañia


class AutoBombero(models.Model):
    clave = models.CharField(max_length=20,default="Desconocido")
    patente = models.CharField(max_length=20,default="Desconocido")
    tipo_vehiculo = models.CharField(max_length=50, default="Desconocido")
    marca = models.CharField(max_length=50, default="Desconocido")
    modelo = models.CharField(max_length=50)
    año = models.IntegerField(validators=[MinValueValidator(1900)], default=1900)
    nro_motor = models.CharField(max_length=100, default="Sin especificar")
    nro_chasis = models.CharField(max_length=150, default="Sin especificar")
    compañia = models.ForeignKey(Compañia, on_delete=models.SET_NULL, null=True)
    imagen = models.ImageField(upload_to="imgprod", null=True)
    
    def __str__(self):
        return self.clave
    
    
class MantencionVehiculo(models.Model):
    ESTADO_CHOICES = [
        ('Bueno', 'Bueno'),
        ('Malo', 'Malo'),
        ('N/A', 'N/A'),
    ]
    
    TIPO_MANTENCION_CHOICES = [
        ('Preventiva', 'Preventiva'),
        ('Correctiva', 'Correctiva'),
        ('Externa', 'Externa'),
    ]
    
    id_autobombero = models.ForeignKey('AutoBombero', on_delete=models.CASCADE)
    fecha_preventiva_ingreso = models.DateField(default=timezone.now)
    fecha_preventiva_entrega = models.DateField(default=timezone.now)
    fecha_correctiva = models.DateField(default=timezone.now)
    fecha_externa = models.DateField(default=timezone.now)
    hora_motor_preventiva = models.TimeField(default='00:00:00')
    hora_bomba_preventiva = models.TimeField(default='00:00:00')
    hora_motor_correctiva = models.TimeField(default='00:00:00')
    hora_bomba_correctiva = models.TimeField(default='00:00:00')
    kilometraje = models.IntegerField(default=0)
    estado_combustible = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_motor_funcionamiento = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_filtro_aire = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_nivel_aceite_motor = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_tablero_instrumentos = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_nivel_refrigerante = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_nivel_aceite_transmision = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_fugas_aceite_aire = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_frenos_servicio_funcionamiento = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_fugas_aire = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_frenos_estacionamiento = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_nivel_liquido_hidraulico = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_liquido_juego_direccion = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_liquido_fugas = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_parabrisas_ventanas = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_carroceria = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_altas_bajas = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_estacionamiento_viraje = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_traseras_frenos = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_reserva_alarma_retroceso = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_bornes_terminales_bateria = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_presion_desgaste_neumaticos = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_llantas = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_sistemas_sonoros_emergencia = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_emergencia = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_luces_tablero_bomba = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_pto_enganche_bomba = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_lecturas_manometros_manovacuometros = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    estado_fugas_general_funcionamiento_bomba = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='N/A')
    observaciones_preventiva = models.TextField(default="Sin observaciones")
    observaciones_correctiva = models.TextField(default="Sin observaciones")
    observaciones_externa = models.TextField(default="Sin observaciones")
    tipo_mantencion = models.CharField(max_length=20, choices=TIPO_MANTENCION_CHOICES, default='Correctiva')
    

    def __str__(self):
        return f'Mantencion Vehículo #{self.id} - Patente: {self.id_autobombero.patente}'
    
    
class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('capitan', 'Capitán'),
        ('mecanico', 'Mecánico'),
        ('comandante', 'Comandante'),
    )
    
    # Agregar un campo de rol
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='mecanico')
    compañia = models.ForeignKey(Compañia, on_delete=models.SET_NULL, null=True, blank=True)
    
    

app_bomberos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import AutoBombero, MantencionVehiculo, Compañia
from .forms import frmVehiculoBomberos, frmMantencionVehiculo, frmMecanicoUser, frmLogin, frmCompañia
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.models import Group



# Create your views here.

def index(request):
    obtener = AutoBombero.objects.all()
    user_role = request.session.get('user_role', None)
    
    usuario_autenticado = request.user

    # Verificar si el usuario es un capitán y tiene una compañía asignada
    if usuario_autenticado.is_authenticated and usuario_autenticado.role == 'capitan' and usuario_autenticado.compañia:
        compañia_capitan = usuario_autenticado.compañia

        # Filtrar los vehículos por la compañía del capitán actual
        obtener = AutoBombero.objects.filter(compañia=compañia_capitan)
    else:
        # Si el usuario no es un capitán o no tiene una compañía asignada, mostrar todos los vehículos
        obtener = AutoBombero.objects.all()
    
    contexto = {
        'obtener': obtener,
        'user_role': user_role, 
    }
    return render(request, 'app_bomberos/index.html', contexto)


def gestion_vehiculos(request):
    obtener = AutoBombero.objects.all()
    return render(request, 'app_bomberos/gestion_vehiculos.html', {
        'obtener': obtener
    })
    

def add_vehiculo(request):
    form=frmVehiculoBomberos(request.POST or None)
    contexto={
        "form":form
    }
    if request.method=="POST":
        form=frmVehiculoBomberos(data=request.POST,files=request.FILES)
        if form.is_valid():
           form.save()
           messages.success(request,"Vehículo Agregado!")

           return redirect(to="gestion_vehiculos")
        
    

    return render(request,"app_bomberos/add_vehiculo.html",contexto)



def update_vehiculo(request,id):
    prod=get_object_or_404(AutoBombero,pk=id)
    form=frmVehiculoBomberos(instance=prod)
    #form.fields["id"].disabled=True
    contexto={
        "form":form
    }

    if request.method=="POST":
        form=frmVehiculoBomberos(data=request.POST,files=request.FILES,instance=prod)
        #form.fields["id"].disabled=False
        if form.is_valid():
            search=AutoBombero.objects.get(pk=prod.id)
            datos_form=form.cleaned_data
            search.clave=datos_form.get("clave")
            search.patente=datos_form.get("patente")
            search.tipo_vehiculo=datos_form.get("tipo_vehiculo")
            search.marca=datos_form.get("marca")
            search.modelo=datos_form.get("modelo")
            search.año=datos_form.get("año")
            search.nro_motor=datos_form.get("nro_motor")
            search.nro_chasis=datos_form.get("nro_chasis")
            search.compañia=datos_form.get("compañia")
            search.imagen=datos_form.get("imagen")
            search.save()
            messages.success(request,"Vehículo Modificado!")
            return redirect(to="gestion_vehiculos")
        contexto["form"]=form
        
    return render(request,"app_bomberos/update_vehiculo.html",contexto)


def delete_vehiculo(request,id):
    v=get_object_or_404(AutoBombero,pk=id)
    contexto={
        "v":v
    }
    if request.method=="POST":
        v.delete()
        messages.success(request,"Vehículo Eliminado!")
        return redirect(to="gestion_vehiculos")

    return render(request,"app_bomberos/delete_vehiculo.html",contexto) 


def detail_vehiculo(request, id):
    v = get_object_or_404(AutoBombero, pk=id)
    form_mantencion = frmMantencionVehiculo(initial={'id_autobombero': v.id})
    user_role = request.session.get('user_role', None)

    if request.method == "POST":
        form_mantencion = frmMantencionVehiculo(request.POST)
        if form_mantencion.is_valid():
            form_mantencion.save(commit=False)
            form_mantencion.instance.id_autobombero = v
            form_mantencion.save()
            messages.success(request,"Mantención Agregada!")
            return redirect(to="index")

    contexto = {
        "v": v,
        "form_mantencion": form_mantencion,
        "user_role": user_role,
    }
    return render(request, "app_bomberos/detail_vehiculo.html", contexto)


def register_m(request):
    user_role = request.session.get('user_role', None)
    if request.method == 'POST':
        form = frmMecanicoUser(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            
            # Establecer la variable de sesión 'user_role' basada en el rol seleccionado
            user_role = form.cleaned_data.get('role')
            request.session['user_role'] = user_role
            
            # Asignar la compañía solo si el rol es "capitán"
            if user_role == 'capitan':
                compañia = form.cleaned_data.get('compañia')
                user.compañia = compañia
                user.save()
            messages.success(request,"Cuenta creada!")
            return redirect('index')  # Redirigir a la página de inicio después del registro
    else:
        form = frmMecanicoUser()
    
    contexto = {
        'form': form,
        'user_role': user_role,
    }
        
    return render(request, 'registration/register_m.html', contexto)




def login_custom(request):
    if request.method == 'POST':
        form = frmLogin(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                
                # Establecer la variable de sesión 'user_role' basada en el rol del usuario
                if user.role:
                    request.session['user_role'] = user.role
                else:
                    # Si el usuario no tiene un rol definido, puedes manejarlo de alguna manera
                    pass
                
                return redirect('index')  # Redirigir a la página de inicio después de iniciar sesión
    else:
        form = frmLogin()
    
    return render(request, 'registration/login_custom.html', {'form': form})



def logout_custom(request):
    logout(request)
    return redirect('index')  # Redirige a la página de inicio después de cerrar sesión


def compañia(request):
    form=frmCompañia(request.POST or None)
    contexto={
        "form":form
    }
    if request.method=="POST":
        form=frmCompañia(data=request.POST,files=request.FILES)
        if form.is_valid():
           form.save()
           messages.success(request,"Compañia Agregada!")

           return redirect(to="index")
       
    return render(request,"app_bomberos/compañia.html",contexto)



def historial_mantenciones(request):
    obtener = MantencionVehiculo.objects.filter(tipo_mantencion='Preventiva')
    user_role = request.session.get('user_role', None)
    
    contexto = {
        'obtener': obtener,
        'user_role': user_role, 
    }
    return render(request, 'app_bomberos/historial_mantenciones.html', contexto)


def historial_correctiva(request):
    obtener = MantencionVehiculo.objects.filter(tipo_mantencion='Correctiva')
    user_role = request.session.get('user_role', None)
    
    contexto = {
        'obtener': obtener,
        'user_role': user_role, 
    }
    return render(request, 'app_bomberos/historial_correctiva.html', contexto)



def historial_externo(request):
    obtener = MantencionVehiculo.objects.filter(tipo_mantencion='Externa')
    user_role = request.session.get('user_role', None)
    
    contexto = {
        'obtener': obtener,
        'user_role': user_role, 
    }
    return render(request, 'app_bomberos/historial_externo.html', contexto)

app_bomberos/templates/app_bomberos/add_vehiculo.html
{% extends "app_bomberos/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Agregar Vehículos{% endblock %}

{% block content %}

<div class="container" style="margin-top: 50px;"> 
    <form class="form" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <h1 style="color: #8d8d8d;">Agregar un vehículo</h1>
    </div>
    <form action="">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                   {{form|crispy}}

                   {% if form %}
                   <input type="submit" value="Guardar" class="btn btn-success">
                   {% endif %}
       
    </form>
</div>

{% endblock %}

app_bomberos/templates/app_bomberos/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Popper.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <title>{% block title %}Sitio Web{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app_bomberos/css/estilo.css' %}">

</head>
<body>
    <header>
        <h1>Bomberos de Chile</h1>
        <nav class="navbar navbar-expand-lg  navbar-dark  ">    
            <div class="collapse navbar-collapse">
              <ul class="navbar-nav mr-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'index' %}">Home</a>
              </ul>
              {% if user.is_staff %}
              <ul class="navbar-nav mr-right">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'gestion_vehiculos' %}">Gestión Vehiculos</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'compañia' %}">Agregar Compañías</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'register_m' %}">Registrar usuario</a>
                </li>
                {%endif%}
                <ul class="navbar-nav mr-right">
                  {% if user.is_authenticated %}
                  <li class="nav-item active ">
                      <a class="nav-link" href="#" onclick="confirmLogout()">
                          Cerrar Sesión
                      </a>
                  </li>
                <ul class="navbar-nav mr-right">
                    {% if user_role == 'capitan' %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Estado de carros</a>
                    </li>
                    {% endif %}
                    {% if user_role == 'mecanico' and not user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'historial_mantenciones'%}">Historial de mantenciones</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Estado de carros</a>
                    </li>
                    {% endif %}
                    {% if user_role == 'comandante' and not user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{%url 'historial_mantenciones'%}">Historial de mantenciones</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Estado de carros</a>
                    </li>
                    {% endif %}
                  {% else %}
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'login_custom' %}">Iniciar sesión</a>
                  </li>
                  {% endif %}
              </ul>
              </ul>              
            </div>
          </nav>
    </header>
    <main class="contenido-principal">
        {% block content %}
        
        {% endblock %}
    </main>



        <!-- Pie de página común -->
         <!-- Footer -->
      <footer>
          <p>Author: Gustavo Martínez</p>
          <p><a href="/">gu.martinezb@duocuc.cl</a></p>
      </footer>
 <!-- JavaScript para la confirmación de cierre de sesión -->
 <script>
    function confirmLogout() {
        Swal.fire({
            title: '¿Cerrar Sesión?',
            text: '¿Estás seguro de que deseas cerrar sesión?',
            icon: 'question',
            showCancelButton: true,
            confirmButtonText: 'Sí',
            cancelButtonText: 'Cancelar',
            confirmButtonColor: 'Red'
        }).then(function (result) {
            if (result.isConfirmed) {
                window.location.href = "{% url 'logout_custom' %}";
            }
        });
    }
</script>

</body>
</html>

app_bomberos/templates/app_bomberos/detail_vehiculo.html
{% extends 'app_bomberos/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Mantención{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
            <img class="img-thumbnail img-fluid" src="{{ v.imagen.url }}" alt="Vehículo">
            <h2>{{ v.modelo }}</h2>
            <!-- Otros detalles del vehículo -->
            <p><strong>Clave:</strong> {{ v.clave }}</p>
            <p><strong>Patente:</strong> {{ v.patente }}</p>
            <p><strong>Tipo de vehículo:</strong> {{ v.tipo_vehiculo }}</p>
            <p><strong>Marca:</strong> {{ v.marca }}</p>
            <p><strong>Año:</strong> {{ v.año }}</p>
            <p><strong>N° Motor:</strong> {{ v.nro_motor }}</p>
            <p><strong>N° Chasis:</strong> {{ v.nro_chasis }}</p>
            <p><strong>Compañia:</strong> {{ v.compañia }}</p>
        </div>
        
        
            <!-- Otros detalles del vehículo -->
        
<!--
    <h3>Historial de Mantenimiento</h3>
    <ul>
        {% for mantenimiento in v.mantencionvehiculo_set.all %}
        <li>
            <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#detalleMantencion{{ mantenimiento.id }}">
                Mantenimiento del {{ mantenimiento.fecha }}
            </button>
            <div id="detalleMantencion{{ mantenimiento.id }}" class="collapse">
                <p>Kilometraje: {{ mantenimiento.kilometraje }}</p>
                <p>Número de Motor: {{ mantenimiento.nro_motor }}</p>
            </div>
        </li>
        {% empty %}
        <li>No hay registros de mantenimiento para este vehículo.</li>
        {% endfor %}
    </ul>
      -->
<div class="col-sm-6">
    <!-- Formulario de Mantenimiento -->
    <h3>Registrar Mantenimiento</h3>
    <form method="post">
        {% csrf_token %}

        {{ form_mantencion.tipo_mantencion|as_crispy_field }}

        <div id="campos_preventiva" style="display: none;">
            {# Campos para la mantención preventiva #}
            {{ form_mantencion.fecha_preventiva_ingreso|as_crispy_field }}
            {{ form_mantencion.fecha_preventiva_entrega|as_crispy_field }}
            {{ form_mantencion.hora_motor_preventiva|as_crispy_field }}
            {{ form_mantencion.hora_bomba_preventiva|as_crispy_field }}
            {{ form_mantencion.kilometraje|as_crispy_field }}
            {{ form_mantencion.estado_combustible|as_crispy_field }}
            {{ form_mantencion.estado_motor_funcionamiento|as_crispy_field }}
            {{ form_mantencion.estado_filtro_aire|as_crispy_field }}
            {{ form_mantencion.estado_nivel_aceite_motor|as_crispy_field }}
            {{ form_mantencion.estado_tablero_instrumentos|as_crispy_field }}
            {{ form_mantencion.estado_nivel_refrigerante|as_crispy_field }}
            {{ form_mantencion.estado_nivel_aceite_transmision|as_crispy_field }}
            {{ form_mantencion.estado_fugas_aceite_aire|as_crispy_field }}
            {{ form_mantencion.estado_frenos_servicio_funcionamiento|as_crispy_field }}
            {{ form_mantencion.estado_fugas_aire|as_crispy_field }}
            {{ form_mantencion.estado_frenos_estacionamiento|as_crispy_field }}
            {{ form_mantencion.estado_nivel_liquido_hidraulico|as_crispy_field }}
            {{ form_mantencion.estado_liquido_juego_direccion|as_crispy_field }}
            {{ form_mantencion.estado_liquido_fugas|as_crispy_field }}
            {{ form_mantencion.estado_parabrisas_ventanas|as_crispy_field }}
            {{ form_mantencion.estado_carroceria|as_crispy_field }}
            {{ form_mantencion.estado_luces_altas_bajas|as_crispy_field }}
            {{ form_mantencion.estado_luces_estacionamiento_viraje|as_crispy_field }}
            {{ form_mantencion.estado_luces_traseras_frenos|as_crispy_field }}
            {{ form_mantencion.estado_luces_reserva_alarma_retroceso|as_crispy_field }}
            {{ form_mantencion.estado_bornes_terminales_bateria|as_crispy_field }}
            {{ form_mantencion.estado_presion_desgaste_neumaticos|as_crispy_field }}
            {{ form_mantencion.estado_llantas|as_crispy_field }}
            {{ form_mantencion.estado_sistemas_sonoros_emergencia|as_crispy_field }}
            {{ form_mantencion.estado_luces_emergencia|as_crispy_field }}
            {{ form_mantencion.estado_luces_tablero_bomba|as_crispy_field }}
            {{ form_mantencion.estado_pto_enganche_bomba|as_crispy_field }}
            {{ form_mantencion.estado_lecturas_manometros_manovacuometros|as_crispy_field }}
            {{ form_mantencion.estado_fugas_general_funcionamiento_bomba|as_crispy_field }}
            {{ form_mantencion.observaciones_preventiva|as_crispy_field }}
        </div>

        <div id="campos_correctiva" style="display: none;">
            {# Campos para la mantención correctiva #}
            {{ form_mantencion.fecha_correctiva|as_crispy_field }}
            {{ form_mantencion.hora_motor_correctiva|as_crispy_field }}
            {{ form_mantencion.hora_bomba_correctiva|as_crispy_field }}
            {{ form_mantencion.observaciones_correctiva|as_crispy_field }}
        </div>

        <div id="campos_externa" style="display: none;">
            {# Campos para la mantención externa #}
            {{ form_mantencion.fecha_externa|as_crispy_field }}
            {{ form_mantencion.observaciones_externa|as_crispy_field }}
        </div>
        
        <button type="submit" class="btn btn-primary">Guardar Mantenimiento</button>
    </form>
    <br> 
    
<script>
    const tipoMantencionField = document.querySelector('#id_tipo_mantencion');
const camposPreventiva = document.querySelector('#campos_preventiva');
const camposCorrectiva = document.querySelector('#campos_correctiva');
const camposExterna = document.querySelector('#campos_externa');

tipoMantencionField.addEventListener('change', function () {
  const tipoMantencion = tipoMantencionField.value;

  console.log("Tipo de Mantención:", tipoMantencion);

  // Mostrar u ocultar campos según la selección
  if (tipoMantencion === 'Preventiva') {
    camposPreventiva.style.display = 'block';
    camposCorrectiva.style.display = 'none';
    camposExterna.style.display = 'none';
  } else if (tipoMantencion === 'Correctiva') {
    camposPreventiva.style.display = 'none';
    camposCorrectiva.style.display = 'block';
    camposExterna.style.display = 'none';
  } else if (tipoMantencion === 'Externa') {
    camposPreventiva.style.display = 'none';
    camposCorrectiva.style.display = 'none';
    camposExterna.style.display = 'block';
  } else {
    camposPreventiva.style.display = 'none';
    camposCorrectiva.style.display = 'none';
    camposExterna.style.display = 'none';
  }
});

// Llama a la función inicialmente para manejar la visibilidad inicial
tipoMantencionField.dispatchEvent(new Event('change'));


</script>
    
</div>
</div>
</div>






{% endblock content %}